### ISSUE TITLE
Log missing

### ISSUE THREAD

**Issue by cani1989** [guydavis/machinaris#257]
Logging isn't working after I updated to latest version. I get error:
![image](https://user-images.githubusercontent.com/622305/131376726-8a6a82e8-72a0-4cdc-8038-4f69abb068d0.png)

**Comment by aktin45** [comment]
I'm also having this same issue. Thanks!

**Comment by guydavis** [comment]
Hi, this should be fixed in v0.5.4.  Please let me know if you encounter if further.  Thanks!

**Comment by cani1989** [comment]
It works under 'Plotting', but under 'Farming' it still shows the same error. I am using v0.5.4.

**Comment by guydavis** [comment]
Ok, my mistake for not catching both spots.  This will be fixed in next release.  Re-opening issue.

**Comment by guydavis** [comment]
Closing as available in v0.5.5.
